trigger: [master]
pr: [master]
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master

pool:
  vmImage: "windows-latest"

variables:
  patch: $[counter('versioncounter', 1)]

name: 1.0.$(patch)

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: "test"
